/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package klarigi

class App {
  static void main(String[] args) {
    def cliBuilder = new CliBuilder(
      usage: 'klarigi [<options>]',
      header: 'Options:'
    )

    cliBuilder.with {
      h longOpt: 'help', 'Print this help text and exit.'

            // all options
      _ longOpt: 'out', 'Where to write the annotation results.', args: 1
      _ longOpt: 'append', 'Append output file, instead of replacing it', type: Boolean
      _ longOpt: 'verbose', 'Verbose output, mostly progress', type: Boolean, args: 0
      _ longOpt: 'threads', 'Number of threads to use for query/annotation processes', type: Integer, args: 1
    }

    if(!args[0]) { println "Must provide command." }
    if(args[0] == '-h' || args[0] == '--help') {
      cliBuilder.usage(); return;
    }

    def o = cliBuilder.parse(args)
    
    if(o.h) { 
      cliBuilder.usage()
    }
  }
}
